FROM tifayuki/java:7

RUN apt-get update && \
    apt-get install -yq --no-install-recommends wget pwgen ca-certificates openssh-client expect && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV TOMCAT_MAJOR_VERSION 8
ENV TOMCAT_MINOR_VERSION 8.0.11
ENV CATALINA_HOME /tomcat
ENV WEBAPPS_HOME /data/webapps
ENV CONFIG_HOME /tmp/conf-pco

# INSTALL TOMCAT
RUN wget -q https://archive.apache.org/dist/tomcat/tomcat-${TOMCAT_MAJOR_VERSION}/v${TOMCAT_MINOR_VERSION}/bin/apache-tomcat-${TOMCAT_MINOR_VERSION}.tar.gz && \
    wget -qO- https://archive.apache.org/dist/tomcat/tomcat-${TOMCAT_MAJOR_VERSION}/v${TOMCAT_MINOR_VERSION}/bin/apache-tomcat-${TOMCAT_MINOR_VERSION}.tar.gz.md5 | md5sum -c - && \
    tar zxf apache-tomcat-*.tar.gz && \
    rm apache-tomcat-*.tar.gz && \
    mv apache-tomcat* tomcat

ADD create_tomcat_admin_user.sh /create_tomcat_admin_user.sh
ADD tunnelSSH4Link /tunnelSSH4Link
ADD run.sh /run.sh
ADD setenv.sh ${CATALINA_HOME}/bin/

RUN chmod +x /*.sh
RUN chmod +x /tunnelSSH4Link
RUN chmod +x ${CATALINA_HOME}/bin/*.sh

EXPOSE 8080
CMD ["/run.sh"]

